regex ignore option

diff --git a/.github/workflows/run_tests.yaml b/.github/workflows/run_tests.yaml
--- a/.github/workflows/run_tests.yaml
+++ b/.github/workflows/run_tests.yaml
@@ -9,7 +9,7 @@ jobs:
           pip install -r requirements.txt
           wget -q https://github.com/broadinstitute/cromwell/releases/download/84/cromwell-84.jar
       - name: Run tests which should pass
-        run:   python watt.py -e cromwell-84.jar -t simple compress_file expect_fail -p $(nproc)
+        run:   python watt.py -e cromwell-84.jar -t simple compress_file expect_fail ignore_line ignore_line_compress -p $(nproc)
       - name: Run tests which should fail
         run: |
           echo "THE FOLLOWING TESTS SHOULD ALL FAIL"
@@ -31,6 +31,14 @@ jobs:
           fi
           if python watt.py -e cromwell-84.jar -w bad_workflow; then
             echo "Test for workflow bad_workflow succeeded which should not have passed."
+            exit 1
+          fi
+          if python watt.py -e cromwell-84.jar -w say_hello -t ignore_lines_fail; then
+            echo "Test ignore_lines_fail for workflow say_hello succeeded which should not have passed."
+            exit 1
+          fi
+          if python watt.py -e cromwell-84.jar -w say_hello -t ignore_lines_compress_fail; then
+            echo "Test ignore_lines_compress_fail for workflow say_hello succeeded which should not have passed."
             exit 1
           fi
           if python watt.py -e cromwell-84.jar -w not_a_workflow; then
